name: "Slack PR Notifier"
description: "Notify a Slack channel when a PR is ready for review"

inputs:
  slack-token:
    description: "Slack bot token (xoxb-...)"
    required: true
  channel:
    description: "Slack channel ID (e.g., C12345678)"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
